global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: 'proposta'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cartao-proposta:9596']